Repository hugo-fixit/FixIt, pull requests merged in 2023-01, with the labels that each got.

#259 :recycle: Refactor(i18n): hierarchize translation fields for supported languages
  CHANGELOG.md
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/it.toml
  i18n/pl.toml
  i18n/pt-BR.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sr.toml
  i18n/vi.toml
  i18n/zh-CN.toml
  i18n/zh-TW.toml
  layouts/_default/section.html
  layouts/_default/single.md
  layouts/_default/summary.html
  layouts/partials/assets.html
  layouts/partials/footer.html
  layouts/partials/head/seo.html
  layouts/partials/header.html
  layouts/partials/init/detection-env.html
  layouts/partials/init/detection-version.html
  layouts/partials/plugin/reward.html
  layouts/partials/recently-updated.html
  layouts/partials/rss/item.html
  layouts/partials/single/comment.html
  layouts/partials/single/expiration-reminder.html
  layouts/partials/single/fixit-decryptor.html
  layouts/partials/single/footer.html
  layouts/partials/single/post-author.html
  layouts/partials/widgets.html
  layouts/posts/single.html
  layouts/shortcodes/admonition.html
  layouts/shortcodes/fixit-encryptor.html
  layouts/shortcodes/version.html
  layouts/taxonomy/terms.html
Labels: i18n

#267 :memo: Docs: add TikTok social link (#264)
  README.md
  README.zh-cn.md
  assets/data/social.yml
  config.toml
Labels: enhancement

#276 :bug: Fix: sitemap.xml link in robots.txt doesn't point to main sitemap
  layouts/robots.txt
Labels: bug
