Repository hugo-fixit/FixIt, pull requests merged in 2025-04, with the labels that each got.

#579 :bug: Fix: change template lookup order to fit Hugo 0.146.0
  layouts/_default/categories.html
  layouts/_default/collections.html
  layouts/_default/list.html
  layouts/_default/tags.html
  layouts/section/list.html
  layouts/taxonomy/terms.html
Labels: bug

#581 :bug: Fix: deprecated layouts/page directory at Hugo 0.146.0+
  layouts/friends.html
  layouts/search.html
Labels: bug

#585 :bug: Fix: lookup rules of RSS templates
  layouts/_default/home.rss.xml
  layouts/_default/list.rss.xml
  layouts/_default/term.rss.xml
Labels: bug

#587 :sparkles: Feat: add echarts shortcode and code fences support JS object literal
  assets/js/theme.js
  layouts/partials/plugin/echarts.html
  layouts/shortcodes/echarts.html
Labels: enhancement

#589 :recycle: Refactor: change templates lookup order
  layouts/_default/friends.html
  layouts/_default/search.html
  layouts/_default/section.html
  layouts/_default/section.rss.xml
  layouts/_default/term.html
  layouts/_default/terms.html
Labels: hugo

#590 Feat: add `hugo.mainSections` param support
  hugo.toml
  layouts/_default/_markup/render-heading.html
  layouts/partials/init/global.html
Labels: enhancement

#592 :sparkles: Feat: add `async` and `data` params for echarts shortcode
  assets/js/theme.js
  assets/js/util.js
  layouts/partials/plugin/echarts.html
  layouts/shortcodes/echarts.html
Labels: enhancement

#594 Style: hide scrollbar in print media
  assets/css/_core/_media.scss
Labels: enhancement

#595 :sparkles: Feat: add `data` and `file` params support for timeline sh…
  layouts/_default/_markup/render-codeblock-timeline.html
  layouts/partials/plugin/timeline.html
  layouts/shortcodes/timeline.html
Labels: enhancement
